### ISSUE TITLE
..

### ISSUE THREAD

**Issue by dumitruds** [Bhai4You/Ip-Attack#9]
sh: toilet: inaccessible or not found

<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

sh: toilet: inaccessible or not found

error getting results

sh: toilet: inaccessible or not found

No PTR records found

sh: toilet: inaccessible or not found

**Comment by Bhai4You** [comment]
maybe toilet package is not installed on your termux. you can install it by this command ```pkg install toilet```.
